services:
    # ...
    admin.lycan.provider.rentivo:
        class: Lycan\Providers\RentivoBundle\Admin\ProviderRentivoAdmin
        arguments: [~, Lycan\Providers\RentivoBundle\Entity\ProviderRentivoAuth, CoreBundle:CRUD ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Providers, label: Rentivo }

    lycan.rabbit.consumer.pull_provider.rentivo:
        class : Lycan\Providers\RentivoBundle\Consumer\PullProviderConsumer
        arguments:  [@app.logger.console, @doctrine.orm.entity_manager ]
        calls:
            - [ setContainer,[ @service_container ] ]

    lycan.rabbit.consumer.pull_listing.rentivo:
        class : Lycan\Providers\RentivoBundle\Consumer\PullListingConsumer
        arguments:  [@app.logger.console, @doctrine.orm.entity_manager ]
        calls:
            - [ setContainer,[ @service_container ] ]

    lycan.rabbit.consumer.pull_provider.tabs:
            class : Lycan\Providers\TabsBundle\Consumer\PullProviderConsumer
            arguments:  [@app.logger.console, @doctrine.orm.entity_manager ]
            calls:
                - [ setContainer,[ @service_container ] ]

    lycan.rabbit.consumer.pull_listing.tabs:
        class : Lycan\Providers\TabsBundle\Consumer\PullListingConsumer
        arguments:  [@app.logger.console, @doctrine.orm.entity_manager ]
        calls:
            - [ setContainer,[ @service_container ] ]

