
services:
    # ...
    admin.lycan.provider.rentivo:
        class: Lycan\Providers\RentivoBundle\Admin\ProviderRentivoAdmin
        arguments: [~, Lycan\Providers\RentivoBundle\Entity\ProviderRentivoAuth, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Providers, label: Rentivo }
