services:
    # ...

     admin.lycan.batch_executions:
            class: Lycan\Providers\CoreBundle\Admin\BatchExecutionsAdmin
            arguments: [~, Lycan\Providers\CoreBundle\Entity\BatchExecutions,  CoreBundle:CRUD  ]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Executions, label: Jobs }
            calls:
                - [ setContainer,[ @service_container ] ]
                - [ addChild, ['@admin.lycan.events']]

     admin.lycan.events:
            class: Lycan\Providers\CoreBundle\Admin\EventsAdmin
            arguments: [~, Lycan\Providers\CoreBundle\Entity\Event,  CoreBundle:CRUD  ]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Executions, label: Events }
            calls:
                - [ setContainer,[ @service_container ] ]
                - [ setTemplate, [ list, CoreBundle:Admin/Events:list.html.twig ]]

