<?php

namespace Lycan\Providers\CoreBundle\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection;
use Sonata\AdminBundle\Admin\AdminInterface;
use Knp\Menu\ItemInterface as MenuItemInterface;
use AppBundle\Admin\BaseAdmin as BaseAdmin;

class EventsAdmin extends BaseAdmin
{
	protected $parentAssociationMapping = 'batch';
	protected $baseRoutePattern = 'events';
	
	
	protected $datagridValues = array(
		'_page' => 1,
		'_sort_order' => 'DESC',
		'_sort_by' => 'createdAt',
	);
	
	
	protected $container;
	public function setContainer($container){
		$this->container = $container;
	}
	
	protected function configureRoutes(RouteCollection $collection) {
		// to remove a single route
		$collection->remove('delete');
		$collection->remove('create');
	
	}
	
	
	/**
	 * @return array
	 */
	public function getFilterParameters()
	{
		$parameters = parent::getFilterParameters();
		// $admin = $this->isChild() ? $this->getParent() : $this;
		
		if($this->getParent()) {
			$parameters = array_merge($parameters, [
				'property' => ['value' => (string)$this->getParent()
					->getSubject()
					->getId()]
			]);
		}
		
		
		return $parameters;
	}
	
	
	
	public function getBatchActions()
	{
		$actions = parent::getBatchActions();
		unset($actions['delete']);
		
		return $actions;
	}
	
	protected function configureShowFields(ShowMapper $showMapper)
	{
		// here we set the fields of the ShowMapper variable,
		// $showMapper (but this can be called anything)
		$showMapper
			->tab('General') // the tab call is optional
				->with('Event Output', array(
					'class'       => 'col-md-12',
					'box_class'   => 'box box-solid',
					'description' => 'Lorem ipsum'))
					->add('log')
				->end()
			
				->with('Context', array(
					'class'       => 'col-md-7',
					'box_class'   => 'box box-solid',
					'description' => 'Lorem ipsum'))
					->add('input', 'data')
					->add('output', 'data')
					->add('serverData', 'data')
					->add('context', 'data' )
				->end()
				->with('Batch Execution', array(
					'class'       => 'col-md-5',
					'box_class'   => 'box box-solid',
					'description' => 'Lorem ipsum'))
					->add('id')
					->add('batch', null, array(
						'route' => array(
							'name' => 'show'
						)))
					->add('eventGroup')
					->add('property', null, array(
						'route' => array(
							'name' => 'edit'
						)))
					->add('levelValue')
					->add('createdAt')
					->add('updatedAt')
				->end()
			->end()
		;
		
	}
	
	public function setTemplate($name, $template)
	{
		
		parent::setTemplate($name, $template); // TODO: Change the autogenerated stub
	}
	
	
	public function createQuery($context = 'list')
	{
		$proxyQuery = parent::createQuery('list');
		// Default Alias is "o"
	
		return $proxyQuery;
	}
	
	
	protected function configureDatagridFilters(DatagridMapper $datagridMapper)
	{
		$datagridMapper->add('eventGroup')
			->add('batch')
			->add('property')
			;
	}
	
	
	protected function configureListFields(ListMapper $listMapper)
	{
		// app.request.get('_sonata_admin')
		$this->container->get('request')->request->set('_sonata_admin', 'admin_app_log_list');
	
		
		$listMapper
		->addIdentifier('id', null, array(
			'route' => array(
				'name' => 'show'
			)
		));
		
		$listMapper->add('level', 'html');
		
		if(!$this->isChild()) {
			$listMapper->add('batch', null, array(
				'route' => array(
					'name' => 'show'
				)));
			
			
		}
		$listMapper->add('eventGroup');
		$listMapper->add('log');
		$listMapper->add('createdAt', 'datetime' ,  array('date_format' => 'yyyy-MM-dd HH:mm:ss') );
		$listMapper->add('_action', 'actions', array(
		'actions' => array(
			// 'CoreBundle:CRUD:list__action_pull.html.twig'
			'show' =>  array(),
		)
	));
		
		
		
	}
	
	
	protected function configureSideMenu(MenuItemInterface $menu, $action, AdminInterface $childAdmin = null)
	{
		
		
	}
	
	
	
	
}