services:
    admin.property:
        class: AppBundle\Admin\PropertyAdmin
        arguments: [~, AppBundle\Entity\Property, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rentals, label: Show Properties }
        calls:
            - [ addChild, ['@admin.lycan.events']]
            - [addChild, ['@admin.channel.listings']]


    admin.channel.listings:
        class: AppBundle\Admin\ListingAdmin
        arguments: [~, AppBundle\Entity\Listing, SonataAdminBundle:CRUD ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rentals, label: Channel Listings }
        calls:
            - [ addChild, ['@admin.lycan.events']]
            # - [ setTemplate, ['inner_list_row',   AppBundle:Admin/ListingAdmin:list__flat_inner_row.html.twig ]]
            # - [ setTemplate, ['base_list_field',  AppBundle:Admin/ListingAdmin:list__flat_field.html.twig   ]]

    admin.brand:
        class: AppBundle\Admin\BrandAdmin
        arguments: [~, AppBundle\Entity\Brand, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Brands, label: Show Brands }
        calls:
            - [addChild, ['@admin.brand.user']]
            - [addChild, ['@admin.brand.channel']]
            - [addChild, ['@admin.property']]


    admin.brand.user:
        class: AppBundle\Admin\UserBrandRegistryAdmin
        arguments: [~, AppBundle\Entity\UserBrandRegistry, SonataAdminBundle:CRUD ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Brands, label: Show Members }

    admin.lycan.providers:
        class: Lycan\Providers\CoreBundle\Admin\ProviderAdmin
        arguments: [~, Lycan\Providers\CoreBundle\Entity\ProviderAuthBase, CoreBundle:CRUD  ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Providers, label: All Providers }
        calls:
            - [ setContainer,[ @service_container ] ]
            # - [ setSubClasses, [{ Rentivo : Lycan\Providers\RentivoBundle\Entity\ProviderRentivoAuth }]]
            - [ addBundledSubClasses, ~ ]
            - [addChild, ['@admin.lycan.batch_executions']]



    admin.brand.channel:
        class: AppBundle\Admin\ChannelBrandAdmin
        arguments: [~, AppBundle\Entity\ChannelBrand,  CoreBundle:CRUD ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Brands, label: Channel Connections }
        calls:
            - [ setContainer,[ @service_container ] ]
            # - [ addBundledSubClasses, ~ ]
            # - [ setSubClasses, [{Rentivo : Lycan\Providers\RentivoBundle\Entity\ProviderRentivoAuth }]]



