services:
    app.logger.user_actions:
        class:  AppBundle\Monolog\UserActionsLogger
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: user_actions }

    app.logger.console:
        class:  AppBundle\Monolog\ConsoleLogger
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: console }