<?php
namespace Pristine\Enums;

class ListingTypes {
	const PREFIX = "LISTING::";
	const LISTING_TYPE_APARTMENT 	= self::PREFIX . "APARTMENT";
	const LISTING_TYPE_BARN 		= self::PREFIX . "BARN";
	const LISTING_TYPE_HOUSE 		= self::PREFIX . "HOUSE";
	const LISTING_TYPE_VILLA 		= self::PREFIX . "VILLA";
	const LISTING_TYPE_TOWNHOUSE 	= self::PREFIX . "TOWNHOUSE";
	const LISTING_TYPE_CHALET 		= self::PREFIX . "CHALET";
	const LISTING_TYPE_FARMHOUSE 	= self::PREFIX . "FARMHOUSE";
	const LISTING_TYPE_CASTLE 		= self::PREFIX . "CASTLE";
	const LISTING_TYPE_COTTAGE 		= self::PREFIX . "COTTAGE";
	const LISTING_TYPE_RESORT 		= self::PREFIX . "RESORT";
	const LISTING_TYPE_BNB 			= self::PREFIX . "BNB";
	const LISTING_TYPE_HOTEL 		= self::PREFIX . "HOTEL";
	const LISTING_TYPE_BOAT			= self::PREFIX . "BOAT";
	const LISTING_TYPE_CONDO 		= self::PREFIX . "CONDO";
	const LISTING_TYPE_HOUSEBOAT 	= self::PREFIX . "HOUSE_BOAT";
	const LISTING_TYPE_CABIN 		= self::PREFIX . "CABIN";
	const LISTING_TYPE_HOSTEL 		= self::PREFIX . "HOSTEL";
	const LISTING_TYPE_BEACHHUT 	= self::PREFIX . "BEACH_HUT";
	const LISTING_TYPE_GITE 		= self::PREFIX . "GITE";
	const LISTING_TYPE_STUDIO 		= self::PREFIX . "STUDIO";
	const LISTING_TYPE_BUNGALOW 	= self::PREFIX . "BUNGALOW";
	const LISTING_TYPE_CHATEAU 		= self::PREFIX . "CHATEAU";
	const LISTING_TYPE_CARAVAN 		= self::PREFIX . "CARAVAN";
	const LISTING_TYPE_PENTHOUSE 	= self::PREFIX . "PENTHOUSE";
	const LISTING_TYPE_CAMPERVAN 	= self::PREFIX . "CAMPERVAN";
	const LISTING_TYPE_SUITE 		= self::PREFIX . "SUITE";
}