<?php

namespace Lycan\Providers\CoreBundle;
use Doctrine\ORM\Events as Events;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use Lycan\Providers\CoreBundle\Mapping\DiscriminatorListener;
use Doctrine\Common\Annotations\AnnotationReader;
use Doctrine\Common\Annotations\AnnotationRegistry;
use Sonata\CoreBundle\Form\FormHelper;
class CoreBundle extends Bundle
{
	
	public function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub
		
		// get the doctrine 2 entity manager
		$em = $this->container->get('doctrine.orm.default_entity_manager');

		// create and then add our event!
		$em->getEventManager()->addEventSubscriber( new DiscriminatorListener( $em ) );
		$this->registerFormMapping();
	}
	
	/**
	 * Register form mapping information.
	 */
	public function registerFormMapping()
	{
	
		FormHelper::registerFormTypeMapping(array(
			'lycan_brands' => 'Sonata\UserBundle\Form\Type\SecurityRolesType'
			
		));
		
	}
	
	

}