services:
    entity.event_listener.user:
            class:  AppBundle\Entity\EventListener\UserListener
            arguments: [ @service_container ]
            tags:
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: postFlush }
                - { name: doctrine.event_listener, event: prePersist }
            calls:
                -   [ setContainer,["@service_container"] ]

    entity.event_listener.property:
            class:  AppBundle\Entity\EventListener\PropertyListener
            arguments: [ @service_container ]
            tags:
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: postFlush }
            calls:
                -   [ setContainer,["@service_container"] ]

    entity.event_listener.brand:
            class:  AppBundle\Entity\EventListener\BrandListener
            arguments: [ @service_container ]
            tags:
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: postFlush }
                - { name: doctrine.event_listener, event: prePersist }
            calls:
                -   [ setContainer,["@service_container"] ]

    entity.event_listener.channel:
            class:  AppBundle\Entity\EventListener\ChannelListener
            arguments: [ @service_container ]
            tags:
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: postFlush }
                - { name: doctrine.event_listener, event: prePersist }
            calls:
                -   [ setContainer,["@service_container"] ]



    entity.event_listener.global:
        class:  AppBundle\Entity\EventListener\GlobalListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: prePersist }
        calls:
            -   [ setContainer,["@service_container"] ]

