<?php

namespace AppBundle\Entity\Repository;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function findPropertyByProviderAndExternal($provider, $external){
		$query = $this->_em->createQueryBuilder();
		try {
			return $query->select("p")
				->from("AppBundle:Property", "p")
				->where("p.providerListingId = :providerExternal")
				->andWhere("p.provider = :provider")
				->setParameter("provider", $provider->getId())
				->setParameter("providerExternal", $external)
				->getQuery()
				->getOneOrNullResult();
		} catch (\Exception $e	){
			return null;
		}
	}
	
	
	public function findListingsByProvider($provider, $property){
		$query = $this->_em->createQueryBuilder();
		try {
			$property = $query->select("p")
				->from("AppBundle:Property", "p")
				->leftJoin("p.listings", "l")
				->where("p.id = :propertyId")
				->andWhere("l.provider = :provider")
				->setParameter("provider", $provider->getId())
				->setParameter("propertyId", $property->getId())
				->getQuery()
				->getOneOrNullResult();
			if($property){
				return $property->getListings();
			}
			return null;
			
		} catch (\Exception $e	){
			return null;
		}
	}
	

	
}
