
services:
    # ...
    lycan.provider.api.lovelegacy:
        class: Lycan\Providers\LoveLegacyBundle\API\Client
        factory: [ Lycan\Providers\LoveLegacyBundle\API\Client, getInstance ]
        calls:
            - [ setContainer,[ @service_container ] ]

    lycan.provider.manager.lovelegacy:
        class: Lycan\Providers\LoveLegacyBundle\API\Manager
        calls:
            - [ setContainer,[ @service_container ] ]

    admin.lycan.provider.lovelegacy:
        class: Lycan\Providers\LoveLegacyBundle\Admin\ProviderLoveLegacyAdmin
        arguments: [~, Lycan\Providers\LoveLegacyBundle\Entity\ProviderLoveLegacyAuth, CoreBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Providers, label: Love Legacy }

